name: xus-parser

dependencies: 
  - python=3.9
  - Flask
  - weasyprint
  - pandas
  - bs4
  - regex
  - lxml
  - isodate
  - pip
  - pip:
    - Flask
    - weasyprint 
    - pandas
    - bs4
    - regex
    - lxml
    - isodate