name: xus-parser

dependencies: 
  - sudo apt-get install libpangocairo-1.0-0
  - python=3.10.0
  - Flask
  - weasyprint
  - pandas
  - bs4
  - regex
  - lxml
  - isodate
  - pip
  - pip:
    - Flask
    - weasyprint 
    - pandas
    - bs4
    - regex
    - lxml
    - isodate